language: java
jdk:
  - oraclejdk8
  
addons:
  sonarqube:
    token:
      secure: b6d779e3889c0fb0a9cefc8123332756a15917b1 # encrypted value of your token
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent -DskipTests install sonar:sonar
